__default__:
    account: dpetrov
    partition: normal,hns,dpetrov
    time: 24:00:00
    nodes: 1
    mem: 64G
    ntasks-per-node: 1
    chdir: /scratch/users/bkim331/variant_calling/

all:
    cpus-per-task: 2
    threads: 2
    mem: 4G
    partition: normal,hns,dpetrov,owners

getCompleteBUSCOList:
    cpus-per-task: 2
    threads: 2
    mem: 16G
    partition: normal,hns,dpetrov,owners

filterBUSCO:
    cpus-per-task: 2
    threads: 2
    mem: 16G
    partition: normal,hns,dpetrov,owners

aggregateBUSCO:
    cpus-per-task: 2
    threads: 2
    mem: 16G
    partition: normal,hns,dpetrov,owners

alignBUSCO:
    cpus-per-task: 8
    threads: 8
    mem: 92G
    partition: normal,hns,dpetrov,owners

trimBUSCO:
    cpus-per-task: 2
    threads: 2
    mem: 16G
    partition: normal,hns,dpetrov,owners

iqtreeBUSCO:
    cpus-per-task: 8
    threads: 8
    mem: 16G
    partition: normal,hns,dpetrov,owners

catIQTree:
    cpus-per-task: 2
    threads: 2
    mem: 8G
    partition: normal,hns,dpetrov,owners

makeASTRALTree:
    cpus-per-task: 16
    threads: 16
    mem: 120G
    partition: normal,hns,dpetrov,owners

addTips:
    cpus-per-task: 2
    threads: 2
    mem: 8G
    partition: normal,hns,dpetrov,owners

phyloFitAll:
    cpus-per-task: 2
    threads: 2
    mem: 8G
    partition: normal,hns,dpetrov,owners

phyloBootAll:
    cpus-per-task: 2
    threads: 2
    mem: 8G
    partition: normal,hns,dpetrov,owners

filterBUSCOAA:
    cpus-per-task: 1
    threads: 1
    mem: 4G
    partition: normal,hns,dpetrov,owners

aggregateBUSCOAA:
    cpus-per-task: 2
    threads: 2
    mem: 8G
    partition: normal,hns,dpetrov,owners

alignBUSCOAA:
    cpus-per-task: 8
    threads: 8
    mem: 92G
    partition: normal,hns,dpetrov,owners

backtrans:
    cpus-per-task: 2
    threads: 2
    mem: 8G
    partition: normal,hns,dpetrov,owners

parseGFF:
    cpus-per-task: 2
    threads: 2
    mem: 8G
    partition: normal,hns,dpetrov,owners

make4dSS:
    cpus-per-task: 2
    threads: 2
    mem: 4G
    partition: normal,hns,dpetrov,owners

split4dSS:
    cpus-per-task: 2
    threads: 2
    mem: 32G
    partition: normal,hns,dpetrov,owners

indiv4dMod:
    cpus-per-task: 2
    threads: 2
    mem: 16G
    partition: normal,hns,dpetrov,owners

avg4dMod:
    cpus-per-task: 2
    threads: 2
    mem: 16G
    partition: normal,hns,dpetrov,owners


