# paths to singularity images
singularity_images:
  assembly: "singularity_images/assembly.simg"
  fcsadaptor: "singularity_images/fcs-adaptor.sif"
  fcsgx: "singularity_images/fcsgx.sif"
  tetools: "singularity_images/tetools.simg"
  parabricks: "singularity_images/parabricks.simg"
  pmd: "singularity_images/deepvariant.simg"

# NCBI FCS settings
fcs:
  fcsdir: "/media/bernardkim/working-2/fcs/gxdb/all" #FCS database
  taxid: "7214"    # taxid for Drosophilidae (expected seqs)

# Nanopore settings
# these are chemistry-specific
nanopore:
  guppy_mod: "dna_r9.4.1_450bps_fast.cfg"
  medaka_mod: "r941_min_fast_g507"
  min_qscore: "10"

# Flye assembler settings
# generally use --nano-raw for all assms
flye:
  reads: "--nano-raw"
  flags: "--scaffold --no-alt-contigs"

# Pepper-Margin-DeepVariant model
# --ont_r9_guppy5_sup   for R9.4.1 SUP
# --ont_r10_q20         for R10.4.1 SUP
pmd:
  model: "--ont_r9_guppy5_sup"
  minGQ: "6"
  minDP: "10"
